config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  get 'static_pages/home'

  get 'static_pages/help'
  
  get 'static_pages/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def hello
      render html: "Hello Static World- where is my style????"
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ch3 Sample App</title>
    <%= csrf_meta_tags %> <!-- csrf_meta_tag [prevents] cross-site request forgery (CSRF), a type of malicious web attack -->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li role="presentation" class="active"><%= link_to 'Home', static_pages_home_path %></li> 
        <li role="presentation"><%= link_to 'About', static_pages_about_path %></li>
        <li role="presentation"><%= link_to 'Help', static_pages_help_path %></li>
        <!-- li role="presentation"><a href="#">Profile</a></li -->
      </ul>
    </div>
    <div class="container">
      <h1>My new App</h1>
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1 class = "greeney">StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<h1>Static Home Page</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>